# safelist
branches:
  only:
  - master

language: cpp
sudo: required
#services:
#    - docker
dist: bionic
os: linux
cache:
  directories:
  - $HOME/.cache/bazel
before_install:
  sudo ./docker/build/ci_install.sh
install: true
jobs:
  include:
    - stage: stage-01
      env:
        - JOB=build
      script:
        - ./apollo.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
    - stage: stage-02
      if: branch = master
      env:
        - JOB=cibuild
      script:
        - ./apollo.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"

notifications:
    email:
        on_success: always
        on_failure: always