name: Geek Style

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: docker pull and build 
      run: bash docker/build/start_geek.sh
    - name: docker exec 
      run: bash docker/build/into_geek.sh
    - name: build
      run: ./apollo.sh build
