name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install 
      run: sudo ./docker/build/cyber.x86_64.sh
    - name: build
      run: ./apollo.sh build
